const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader']}: {})});
try{
 const page=await browser.newPage({viewport:{width:1024,height:1366}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.POSTCARD_TEST_URL||'http://127.0.0.1:8765';
 await page.goto(base+'/collections/maker/');await page.locator('#view-back').click();await page.locator('#message').fill('SOME WORDS STAY WITH YOU.');await page.waitForFunction(()=>!document.querySelector('#png').disabled);
 assert.equal(await page.locator('#view-back').getAttribute('aria-pressed'),'true');
 const renders=[];for(const name of ['original','outline','inflated','worn']){await page.locator(`[data-lettering=${name}]`).click();renders.push(await page.locator('#preview').evaluate(c=>c.toDataURL()));}assert.equal(new Set(renders).size,4);
 await page.locator('#view-front').click();const before=await page.locator('#preview').evaluate(c=>c.toDataURL());await page.locator('#message').fill('HELLO 🦄');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('no capture'));assert.equal(await page.locator('#preview').evaluate(c=>c.toDataURL()),before);assert.match(await page.locator('#status').innerText(),/Back text/);assert.ok(await page.locator('#png').isDisabled());
 await page.locator('#view-back').click();assert.match(await page.locator('#preview-state').innerText(),/Back draft/);await page.locator('#message').fill('LOVE YOU');await page.waitForFunction(()=>!document.querySelector('#png').disabled);assert.match(await page.locator('#preview-state').innerText(),/Back preview/);
 // Postal handwriting must reclaim accidental blank rows before declaring overflow.
 const fitting=await page.evaluate(async()=>{
  const {renderCard}=await import('/shared/postcard-renderer.mjs?v=textfit1');
  const {defaults}=await import('/shared/postcard-project.mjs?v=back5');
  const message='\nYou have always been a hero to me. This is a small keepsake to remind you that you have been and still are a hero to countless others !!!\n\nLove you\n\nAlex\n';
  const p={...defaults(),width:150,height:105,postal:true,font:'adam-capture03',lettering:'inflated',message,recipient:'My friend',signature:'23-09-26',qrSide:'back'};
  const qr={getModuleCount:()=>57,isDark:(r,c)=>(r+c)%2===0};
  return [900,1772].map(width=>{
   const c=Object.assign(document.createElement('canvas'),{width,height:Math.round(width*105/150)}),errors=[];
   renderCard(c,p,null,'back',qr,0,errors);const withMessage=c.toDataURL(),fits=c.textFits;
   renderCard(c,{...p,message:''},null,'back',qr);
   return {errors,fits,hasInk:withMessage!==c.toDataURL(),unchanged:p.message===message};
  });
 });
 for(const result of fitting){assert.deepEqual(result.errors,[]);assert.ok(result.hasInk);assert.ok(result.unchanged);assert.ok(result.fits.some(x=>x.startsWith('Message:')));}
 const bounds=await page.locator('#view-back').boundingBox();assert.ok(bounds.height>=64);assert.ok(bounds.width>120);
 await page.locator('#qrEnabled').check();await page.locator('#qrURL').fill('https://example.org');await page.waitForFunction(()=>!document.querySelector('#png').disabled);
 const goodBack=await page.locator('#preview').evaluate(c=>{const x=c.getContext('2d');return Array.from(x.getImageData(0,c.height*.6,c.width*.45,c.height*.25).data);});await page.locator('#message').fill('HELLO 🦄');await page.waitForFunction(()=>document.querySelector('#preview-state').textContent.includes('Back draft'));assert.deepEqual(await page.locator('#preview').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,c.height*.6,c.width*.45,c.height*.25).data)),goodBack);assert.ok(await page.locator('#png').isDisabled());await page.locator('#message').fill('LOVE YOU');await page.waitForFunction(()=>!document.querySelector('#png').disabled);
 const qr=[];for(const name of ['original','outline','inflated','worn']){await page.locator(`[data-lettering=${name}]`).click();qr.push(await page.locator('#qr-thumb').evaluate(c=>c.toDataURL()));}assert.equal(new Set(qr).size,1);
 await page.locator('[data-lettering=outline]').click();
 await page.locator('#font').selectOption('preset');await page.locator('#message').fill('A little music for the journey. '.repeat(5));await page.waitForFunction(()=>!document.querySelector('#png').disabled);assert.match(await page.locator('#text-fit').innerText(),/Message: .* pt/);
 await page.locator('#message').fill('Very long message. '.repeat(42));await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('8 pt minimum'));assert.ok(await page.locator('#png').isDisabled());
 await page.locator('#message').fill('KEEP THIS SONG');await page.locator('#title').fill('A LITTLE MUSIC FOR THE JOURNEY AND SOMETHING TO KEEP');await page.locator('#view-front').click();await page.waitForFunction(()=>!document.querySelector('#png').disabled);assert.match(await page.locator('#text-fit').innerText(),/Title: .* pt/);
 await page.locator('#project-shelf > summary').click();await page.locator('#project-name').fill('For the crew');const dl=page.waitForEvent('download');await page.locator('#save').click();await dl;await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('project shelf'));assert.equal(await page.locator('#saved-projects option').count(),2);
 await page.reload();assert.equal(await page.locator('#message').inputValue(),'');await page.locator('#project-shelf > summary').click();await page.waitForFunction(()=>document.querySelector('#saved-projects').options.length===2);await page.locator('#saved-projects').selectOption({index:1});await page.locator('#reopen-project').click();await page.waitForFunction(()=>document.querySelector('#message').value==='KEEP THIS SONG');assert.equal(await page.locator('#project-name').inputValue(),'For the crew');const firstId=await page.locator('#saved-projects').inputValue();const nextDownload=page.waitForEvent('download');await page.locator('#save').click();const versionFile=await nextDownload;assert.match(versionFile.suggestedFilename(),/For_the_crew--r002--.*\.juicecard\.json$/);await page.waitForFunction(()=>document.querySelector('#saved-projects').options.length===3);assert.notEqual(await page.locator('#saved-projects').inputValue(),firstId);await page.locator('#remove-project').click();await page.waitForFunction(()=>document.querySelector('#saved-projects').options.length===2);await page.locator('#saved-projects').selectOption(firstId);await page.locator('#remove-project').click();await page.waitForFunction(()=>document.querySelector('#saved-projects').options.length===1);
 await page.locator('#view-back').click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(process.env.QA_OUTPUT||'/tmp','next-pass-back.png')});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.goto(base+'/discover/');await page.screenshot({path:path.join(process.env.QA_OUTPUT||'/tmp','discover-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.goto(base+'/collections/maker/lettering-proof.html');await page.waitForFunction(()=>document.querySelectorAll('#proofs canvas').length===4);await page.setViewportSize({width:1120,height:1100});await page.screenshot({path:path.join(process.env.QA_OUTPUT||'/tmp','lettering-proof.png'),fullPage:true});assert.deepEqual(errors,[]);
 console.log('PASS: four lettering appearances, unchanged QR, front/back switching, overflow preview recovery, 64px side controls, mobile layout and lettering proof');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
